spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fixhub_db
    username: fixhub
    password: fixhub

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: localhost
    port: 1025
    username: mailadmin
    password: mailadmin
    properties:
      mail:
        smtp:
          trust: "*"
        auth: auto
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  frontend-url: http://localhost:8081
  admin:
    email: admin@fixhub.com
    password: ${FIXHUB_ADMIN_PASSWORD:changeme-local-only}