CREATE TABLE identity_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(320) NOT NULL,
    email_normalized VARCHAR(320) NOT NULL,
    phone VARCHAR(16),
    preferred_locale VARCHAR(35) NOT NULL,
    status VARCHAR(32) NOT NULL,
    version BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_identity_accounts PRIMARY KEY (id),
    CONSTRAINT uq_identity_accounts_email_normalized UNIQUE (email_normalized),
    CONSTRAINT ck_identity_accounts_email_not_blank CHECK (BTRIM(email) <> ''),
    CONSTRAINT ck_identity_accounts_email_normalized_not_blank
        CHECK (BTRIM(email_normalized) <> ''),
    CONSTRAINT ck_identity_accounts_phone_e164
        CHECK (phone IS NULL OR phone ~ '^\+[1-9][0-9]{1,14}$'),
    CONSTRAINT ck_identity_accounts_preferred_locale_not_blank
        CHECK (BTRIM(preferred_locale) <> ''),
    CONSTRAINT ck_identity_accounts_status
        CHECK (status IN ('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'DISABLED')),
    CONSTRAINT ck_identity_accounts_version_non_negative CHECK (version >= 0)
);

CREATE UNIQUE INDEX uq_identity_accounts_phone
    ON identity_accounts (phone)
    WHERE phone IS NOT NULL;
