CREATE TABLE identity_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id BIGINT NOT NULL,
    credential_type VARCHAR(32) NOT NULL,
    secret_hash VARCHAR(512) NOT NULL,
    version BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_identity_credentials PRIMARY KEY (id),
    CONSTRAINT fk_identity_credentials_account FOREIGN KEY (account_id)
        REFERENCES identity_accounts (id) ON DELETE RESTRICT,
    CONSTRAINT uq_identity_credentials_account_type UNIQUE (account_id, credential_type),
    CONSTRAINT ck_identity_credentials_type CHECK (credential_type = 'PASSWORD'),
    CONSTRAINT ck_identity_credentials_secret_format
        CHECK (secret_hash ~ '^\{[^{}]*[^{}[:space:]][^{}]*\}.*[^[:space:]].*$'),
    CONSTRAINT ck_identity_credentials_version_non_negative CHECK (version >= 0)
);
