CREATE TABLE identity_email_verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id BIGINT NOT NULL,
    token_digest BYTEA NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    terminal_reason VARCHAR(16),
    terminal_at TIMESTAMP(6) WITH TIME ZONE,
    version BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_identity_email_verification_tokens PRIMARY KEY (id),
    CONSTRAINT fk_identity_email_verification_tokens_account FOREIGN KEY (account_id)
        REFERENCES identity_accounts (id) ON DELETE RESTRICT,
    CONSTRAINT uq_identity_email_verification_tokens_digest UNIQUE (token_digest),
    CONSTRAINT ck_identity_email_verification_tokens_digest_length
        CHECK (octet_length(token_digest) = 32),
    CONSTRAINT ck_identity_email_verification_tokens_terminal_reason
        CHECK (terminal_reason IS NULL OR terminal_reason IN
            ('CONSUMED', 'SUPERSEDED', 'EXPIRED', 'INVALIDATED')),
    CONSTRAINT ck_identity_email_verification_tokens_terminal_pair
        CHECK ((terminal_reason IS NULL AND terminal_at IS NULL)
            OR (terminal_reason IS NOT NULL AND terminal_at IS NOT NULL)),
    CONSTRAINT ck_identity_email_verification_tokens_expiry_after_creation
        CHECK (expires_at > created_at),
    CONSTRAINT ck_identity_email_verification_tokens_version_non_negative CHECK (version >= 0)
);

CREATE UNIQUE INDEX uq_identity_email_verification_tokens_open_account
    ON identity_email_verification_tokens (account_id)
    WHERE terminal_reason IS NULL;

CREATE INDEX ix_identity_email_verification_tokens_open_expires_at
    ON identity_email_verification_tokens (expires_at, id)
    WHERE terminal_reason IS NULL;

CREATE INDEX ix_identity_email_verification_tokens_terminal_at
    ON identity_email_verification_tokens (terminal_at, id)
    WHERE terminal_reason IS NOT NULL;
