CREATE TABLE identity_rate_limit_buckets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    policy VARCHAR(32) NOT NULL,
    key_version INTEGER NOT NULL,
    key_digest BYTEA NOT NULL,
    window_start TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    window_end TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    request_count BIGINT NOT NULL,
    cooldown_until TIMESTAMP(6) WITH TIME ZONE,
    retention_expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_identity_rate_limit_buckets PRIMARY KEY (id),
    CONSTRAINT ck_identity_rate_limit_buckets_policy
        CHECK (policy IN ('REGISTRATION_EMAIL', 'REGISTRATION_ORIGIN', 'RESEND_EMAIL',
            'RESEND_ORIGIN', 'VERIFICATION_ORIGIN', 'FH011_GLOBAL')),
    CONSTRAINT ck_identity_rate_limit_buckets_key_version_positive CHECK (key_version > 0),
    CONSTRAINT ck_identity_rate_limit_buckets_digest_length CHECK (octet_length(key_digest) = 32),
    CONSTRAINT ck_identity_rate_limit_buckets_window_order CHECK (window_end > window_start),
    CONSTRAINT ck_identity_rate_limit_buckets_count_positive CHECK (request_count > 0),
    CONSTRAINT ck_identity_rate_limit_buckets_cooldown
        CHECK (cooldown_until IS NULL OR
            (policy = 'RESEND_EMAIL' AND cooldown_until >= window_start)),
    CONSTRAINT ck_identity_rate_limit_buckets_retention_order
        CHECK (retention_expires_at >= GREATEST(window_end,
            COALESCE(cooldown_until, window_end)) + INTERVAL '24 hours'),
    CONSTRAINT ck_identity_rate_limit_buckets_version_non_negative CHECK (version >= 0),
    CONSTRAINT uq_identity_rate_limit_buckets_key
        UNIQUE (policy, key_version, key_digest, window_start)
);

CREATE INDEX ix_identity_rate_limit_buckets_retention_expires_at
    ON identity_rate_limit_buckets (retention_expires_at, id);
